{
 "title": "Blitzer.de Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Zuletzt aktualisiert",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "misc_info", "legendFormat": "{{last_changed}}" }
   ]
  },
  {
   "title": "Info",
   "type": "stat",
   "gridPos": { "h": 2, "w": 19, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "misc_info", "legendFormat": "{{notes_editorial}}" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mobile_speed_cams", "legendFormat": "Mobile Blitzer" },
    { "expr": "partly_fixed_speed_cams", "legendFormat": "Halbfeste Blitzer" },
    { "expr": "danger_spots", "legendFormat": "Gefahren" }
   ]
  },
  {
   "title": "Aktive Nutzer",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 5, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "user_cnt", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Störungen",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 10, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "misc_info", "legendFormat": "{{notes_it}}" }
   ]
  },
  {
   "title": "Warnungen",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "danger_spots", "legendFormat": "Gefahren" },
    { "expr": "mobile_speed_cams", "legendFormat": "Mobile Blitzer" },
    { "expr": "partly_fixed_speed_cams", "legendFormat": "Stationäre Blitzer" },
    { "expr": "roadworks", "legendFormat": "Baustellen" }
   ]
  },
  {
   "title": "Aktive Nutzer",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "targets": [
    { "expr": "user_cnt >0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Mobile Blitzer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "expr": "mobile_speed_cams > 0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Stationäre Blitzer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "targets": [
    { "expr": "partly_fixed_speed_cams > 0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Feste Blitzer",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 29 },
   "targets": [
    { "expr": "fixed_speed_cams > 0", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Gefahren",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 34 },
   "targets": [
    { "expr": "danger_spots > 0", "legendFormat": "__auto" }
   ]
  }
 ]
}